import type { Locale } from "../i18n";

const EN = {
  "feature.unavailable": "Not available yet",
  "strategy.unavailable": "Elite targeting and automatic device maintenance are not available yet. Legacy selections use Cleaning.",
  "upgrade.unavailable": "Not available yet: maintenance is free. Existing saved levels are retained without an active effect.",
  "device.manage": "Manage devices",
  "device.live": "This control does not pause the campaign.",
  "device.scrollUp": "View devices above",
  "device.scrollDown": "View devices below",
  "device.empty": "No devices placed. Open the shop to place one.",
  "device.capacity": "Capacity {used} / {capacity} · sealed residues {count}",
  "device.life": "Remaining life {value}%",
  "device.refund": "Removal refund: {value} Parts",
  "device.maintain": "Release residues",
  "device.remove": "Remove device",
  "device.cleanup": "Maintenance releases residues onto the ground. Collect them and empty the bag into the bin to finish cleaning. Lifetime use is not restored.",
  "device.nonempty": "Release all residues before removing this catcher.",
  "device.maintained": "Residues released. Collect them and empty the bag into the bin to finish cleaning.",
  "device.removed": "Device removed; the remaining-life refund has been credited.",
  "error.missingTrap": "This device no longer exists or is not a catcher.",
  "error.invalidTrap": "Invalid device ID.",
  "error.emptyTrap": "This catcher has no residues to release.",
  "error.blockedDevice": "This action is unavailable in the current campaign state.",
  "error.refund": "The device refund could not be applied. Refresh and try again.",
  "error.changed": "The campaign state has changed. Check the current controls and try again.",
  "error.conflict": "This request was already used for a different action. Use the current controls to retry.",
  "error.operation": "The operation could not be completed. Refresh and try again.",
  "app.label": "Desktop Creatures campaign controls",
  "toolbar.task": "Current task",
  "toolbar.parts": "Parts: {count}",
  "toolbar.pollution": "Pollution: {percent}%",
  "toolbar.infestation": "Infestation: {percent}%",
  "toolbar.homes": "Homes",
  "toolbar.tools": "Tools",
  "toolbar.shop": "Shop",
  "toolbar.strategy": "Strategy",
  "toolbar.settings": "Settings",
  "toolbar.pause": "Pause",
  "toolbar.resume": "Resume",
  "toolbar.scrollUp": "View controls above",
  "toolbar.scrollDown": "View controls below",
  "toolbar.pausedBy": "Paused: {reasons}",
  "panel.close": "Close panel",
  "panel.shop": "In-run shop",
  "panel.research": "Research",
  "panel.strategy": "Companion strategy",
  "panel.result": "Mission result",
  "panel.settings": "Settings",
  "shop.balance": "Available Parts: {count}",
  "shop.upgrades": "Run upgrades",
  "shop.devices": "Devices and support",
  "shop.currentNext": "Current {current} → after purchase {next}",
  "shop.level": "Level {level} of 3",
  "shop.max": "Maximum level reached",
  "shop.buy": "Buy for {cost} Parts",
  "shop.cannotAfford": "Need {cost} Parts",
  "shop.place": "Choose placement · {cost} Parts",
  "research.balance": "Research Points: {count}",
  "research.freeRespec": "Reset all research for free",
  "research.buy": "Unlock for {cost} Research Points",
  "research.owned": "Unlocked",
  "research.locked": "Requires {id}",
  "research.demoLocked": "Available in the full campaign",
  "strategy.help": "Set independent priorities. These controls send requests; simulation remains authoritative.",
  "strategy.cleaner": "Cleaner",
  "strategy.frog": "Frog",
  "strategy.stamina": "Stamina {value}%",
  "strategy.inventory": "Inventory {used} / {capacity}",
  "strategy.priority": "Priority",
  "priority.clean": "Cleaning",
  "priority.nearHome": "Bugs near home",
  "priority.elite": "Elite enemies",
  "priority.maintenance": "Device maintenance",
  "retreat.title": "Companions are taking shelter",
  "retreat.body": "Prepare for manual cleanup. Tools, the shop, and pause remain available.",
  "siege.title": "Siege in progress",
  "siege.body": "Destroy the main nest, lower infestation and pollution, and protect at least one home.",
  "home.cleaner": "Cleaner home",
  "home.frog": "Frog home",
  "home.hp": "{current} of {maximum} HP",
  "home.fallen": "Fallen",
  "home.repair": "Repair 25% · 25 Parts",
  "home.repairUsed": "Repair already used",
  "home.repairUnavailable": "Repair is available only during a siege",
  "result.victory": "Mission complete",
  "result.defeat": "Mission failed",
  "result.abandoned": "Mission abandoned",
  "result.reason": "Reason: {reason}",
  "result.partsSpent": "Parts spent",
  "result.effectiveActions": "Effective action score",
  "result.peakInfestation": "Peak infestation",
  "result.research": "Research Points earned",
  "result.retry": "Try again",
  "result.continue": "Continue to research",
  "failure.bothHomes": "Both homes have fallen.",
  "failure.abandoned": "The mission was ended by the player; only completed actions count.",
  "failure.unknown": "The campaign ended without a recorded player-facing reason.",
  "tool.bag": "Collection Bag",
  "tool.swatter": "Electric Swatter",
  "tool.trap": "Traps and devices",
  "tool.exit": "Exit tool mode",
  "tool.available": "Available",
  "tool.active": "Active — press Escape to exit",
  "tool.full": "Full — drag the bag to a bin",
  "tool.overheated": "Overheated — release and allow it to cool",
  "tool.cooling": "Cooling: {percent}% heat",
  "tool.blocked": "Unavailable while the campaign is frozen",
  "tool.capacity": "Capacity {used} / {capacity}",
  "settings.language": "Language",
  "settings.uiScale": "UI scale",
  "settings.quality": "Graphics quality",
  "settings.intensity": "Campaign intensity",
  "settings.detection": "Desktop detection",
  "settings.display": "Next run display",
  "settings.displayDisconnected": "Disconnected (saved selection) · {id}",
  "settings.audio": "Audio",
  "settings.master": "Master volume",
  "settings.music": "Music volume",
  "settings.effects": "Effects volume",
  "settings.alerts": "Alert volume",
  "settings.visual": "Visual intensity",
  "settings.motion": "Motion effects",
  "settings.flashes": "Flashes",
  "settings.stains": "Stains",
  "settings.swarm": "Swarm atmosphere",
  "settings.visualAlerts": "Visual alerts remain enabled even when sound is muted.",
  "settings.tutorial": "Show tutorial prompts",
  "settings.panelPause": "Pause while panels are open",
  "settings.diagnostics": "Include anonymous local fault counts in manual support export",
  "display.currentRun": "Current run display",
  "display.current": "Current: {display}",
  "display.open": "Move current run",
  "display.close": "Close display controls",
  "display.help": "Moves this active run. The display choice in Settings applies when the next run starts.",
  "display.choose": "Choose a destination display",
  "display.page": "Displays {current} of {total}",
  "display.previous": "Previous displays",
  "display.next": "Next displays",
  "display.primary": "Primary display",
  "display.details": "{width} × {height} physical pixels · {scale}% scale",
  "display.confirmTitle": "Move to {display}?",
  "display.confirmBody": "The overlay and this active run will move together. Confirm only if you can see and use that display.",
  "display.confirm": "Confirm move",
  "display.cancel": "Cancel",
  "display.moving": "Moving this run to {display}…",
  "display.moved": "This run moved to {display}.",
  "display.failed": "The run could not move. From the tray, enable controls, check the display list, and try again.",
  "display.stale": "That display is no longer available. Choose another display.",
  "display.unavailable": "Current-run display controls are unavailable. From the tray, enable controls and retry after the native display service reconnects.",
  "display.awaiting": "The overlay moved and is waiting for a fresh desktop surface.",
  "display.topologyChanged": "The display layout changed. From the tray, enable controls and refresh the list before moving this run.",
  "display.noOther": "No other display is currently available.",
  "display.retry": "Try again",
  "display.refresh": "Refresh displays",
  "option.low": "Low",
  "option.medium": "Medium",
  "option.high": "High",
  "option.gentle": "Gentle",
  "option.standard": "Standard",
  "option.intense": "Intense",
  "option.desktop": "Desktop",
  "option.practice": "Practice",
  "option.off": "Off",
  "option.reduced": "Reduced",
  "option.full": "Full",
  "tutorial.title": "Tutorial",
  "tutorial.step": "Step {current} of {total}",
  "tutorial.dismiss": "Got it",
  "tutorial.skipStep": "Skip this step",
  "tutorial.skipAll": "Skip tutorial",
  "pause.user": "player pause",
  "pause.shop": "shop open",
  "pause.research": "research open",
  "pause.settings": "settings open",
  "pause.tutorial": "tutorial prompt",
  "pause.detection": "desktop detection unavailable",
  "pause.hidden": "emergency hide",
  "pause.unknown": "system hold ({id})",
  "upgrade.cleanerClean": "Cleaner speed",
  "upgrade.cleanerMove": "Cleaner movement",
  "upgrade.cleanerCapacity": "Cleaner inventory",
  "upgrade.frogTongue": "Frog tongue reach",
  "upgrade.frogAttack": "Frog capture cooldown",
  "upgrade.frogDigestion": "Frog digestion",
  "upgrade.frogBatch": "Frog single capture",
  "upgrade.frogCapacity": "Frog total capacity",
  "upgrade.bagCapacity": "Bag capacity",
  "upgrade.bagEfficiency": "Bag unloading",
  "upgrade.swatDamage": "Swatter damage",
  "upgrade.swatHeat": "Swatter heat capacity",
  "upgrade.trapMaintenance": "Trap maintenance cost",
  "upgrade.homeArmor": "Both homes maximum HP",
  "device.bait": "Bait Station",
  "device.glue": "Glue Pad",
  "device.catcher": "Bug Trap",
  "device.ladder": "Ladder",
  "research.cleaner": "Cleaner",
  "research.frog": "Frog",
  "research.bag": "Collection Bag",
  "research.swat": "Electric Swatter",
  "research.trap": "Traps",
  "research.home": "Homes",
  "lobby.title": "Campaign lobby",
  "lobby.subtitle": "Choose your cleaner and keep your desktop tidy. Trash attracts a living insect ecosystem that you can control through cleaning.",
  "lobby.startTitle": "Demo mission",
  "lobby.startBody": "Trash may carry eggs. Insects hatch, grow, feed and breed; removing their food keeps the population under control. The desktop keeps running after every cleanup.",
  "lobby.start": "Start demo mission",
  "lobby.appearance": "Cleaner appearance",
  "lobby.female": "Female maintenance worker",
  "lobby.femaleBody": "Cream jacket, mint work trousers and a dark ponytail; base abilities are identical.",
  "lobby.male": "Workwear outfit",
  "lobby.maleBody": "Original workwear cleaner; base abilities are identical.",
  "lobby.selected": "Selected",
  "lobby.recent": "Most recent settlement",
  "lobby.noRecent": "No completed mission has been settled on this profile yet.",
  "lobby.mission": "Mission",
  "lobby.run": "Run",
  "lobby.outcome": "Outcome",
  "lobby.score": "Effective score",
  "lobby.reward": "Research Points earned",
  "lobby.researchTitle": "Permanent research",
  "lobby.researchBody": "The demo exposes the first two nodes in each of six branches. Research is purchased only between missions and can be reset for free.",
  "lobby.settingsTitle": "Local settings",
  "outcome.victory": "Victory",
  "outcome.defeat": "Defeat",
  "outcome.abandoned": "Abandoned",
  "feedback.busy": "Saving your choice…",
  "feedback.success": "Choice saved.",
  "feedback.failure": "Action failed ({reason}). Review the message and try again.",
} as const;

export type UiMessageKey = keyof typeof EN;
type TranslationTable = Readonly<Record<UiMessageKey, string>>;

const ZH_CN: TranslationTable = {
  "feature.unavailable": "尚未开放",
  "strategy.unavailable": "精英优先与自动设备维护尚未开放；旧存档选择回退为清洁。",
  "upgrade.unavailable": "尚未开放：当前维护免费。保留已有存档等级，但不产生效果。",
  "device.manage": "设备管理",
  "device.live": "此管理条不暂停战役。",
  "device.scrollUp": "向上查看设备",
  "device.scrollDown": "向下查看设备",
  "device.empty": "尚未放置设备，请在商店选择放置。",
  "device.capacity": "容量 {used} / {capacity} · 密封残渣 {count}",
  "device.life": "剩余寿命 {value}%",
  "device.refund": "移除退款：{value} 零件",
  "device.maintain": "释放残渣",
  "device.remove": "移除设备",
  "device.cleanup": "维护会把残渣释放到地面；还需拾取并整袋投入垃圾桶完成清理。维护不恢复累计使用寿命。",
  "device.nonempty": "先释放全部残渣，才能移除此捕虫箱。",
  "device.maintained": "残渣已释放；还需拾取并整袋投入垃圾桶完成清理。",
  "device.removed": "设备已移除，按剩余寿命计算的退款已入账。",
  "error.missingTrap": "设备已不存在，或不是捕虫箱。",
  "error.invalidTrap": "设备标识无效。",
  "error.emptyTrap": "此捕虫箱没有可释放的残渣。",
  "error.blockedDevice": "当前战役状态下无法执行此操作。",
  "error.refund": "设备退款未能执行，请刷新后重试。",
  "error.changed": "战役状态已变化，请查看当前状态后重试。",
  "error.conflict": "此请求已用于另一项操作，请使用当前控件重试。",
  "error.operation": "操作未能完成，请刷新后重试。",
  "app.label": "桌面生物战役控制",
  "toolbar.task": "当前任务", "toolbar.parts": "零件：{count}", "toolbar.pollution": "污染：{percent}%", "toolbar.infestation": "感染密度：{percent}%", "toolbar.homes": "两屋", "toolbar.tools": "工具", "toolbar.shop": "商店", "toolbar.strategy": "策略", "toolbar.settings": "设置", "toolbar.pause": "暂停", "toolbar.resume": "继续", "toolbar.scrollUp": "向上查看控制项", "toolbar.scrollDown": "向下查看控制项", "toolbar.pausedBy": "已暂停：{reasons}",
  "panel.close": "关闭面板", "panel.shop": "局内商店", "panel.research": "研究", "panel.strategy": "伙伴策略", "panel.result": "任务结果", "panel.settings": "设置",
  "shop.balance": "可用零件：{count}", "shop.upgrades": "局内升级", "shop.devices": "设备与支援", "shop.currentNext": "当前 {current} → 购买后 {next}", "shop.level": "等级 {level} / 3", "shop.max": "已达最高等级", "shop.buy": "花费 {cost} 零件购买", "shop.cannotAfford": "需要 {cost} 零件", "shop.place": "选择位置 · {cost} 零件",
  "research.balance": "研究点：{count}", "research.freeRespec": "免费重置全部研究", "research.buy": "花费 {cost} 研究点解锁", "research.owned": "已解锁", "research.locked": "需要前置章：{id}", "research.demoLocked": "完整版战役中开放",
  "strategy.help": "分别设置行动优先级。这些控件只发送请求，模拟仍是最终权威。", "strategy.cleaner": "青年", "strategy.frog": "青蛙", "strategy.stamina": "体力 {value}%", "strategy.inventory": "库存 {used} / {capacity}", "strategy.priority": "优先级", "priority.clean": "清洁", "priority.nearHome": "近屋虫", "priority.elite": "精英", "priority.maintenance": "设备维护",
  "retreat.title": "伙伴正在回家", "retreat.body": "准备手动清理；工具、商店和暂停仍可使用。", "siege.title": "围攻进行中", "siege.body": "摧毁主虫巢、降低感染与污染，并保护至少一座家。",
  "home.cleaner": "青年之家", "home.frog": "蛙屋", "home.hp": "生命 {current} / {maximum}", "home.fallen": "已倒塌", "home.repair": "修复 25% · 25 零件", "home.repairUsed": "本轮修复已使用", "home.repairUnavailable": "仅围攻阶段可修复",
  "result.victory": "任务完成", "result.defeat": "任务失败", "result.abandoned": "已放弃任务", "result.reason": "原因：{reason}", "result.partsSpent": "已花零件", "result.effectiveActions": "有效行动分数", "result.peakInfestation": "最高感染密度", "result.research": "获得研究点", "result.retry": "再试一次", "result.continue": "前往研究",
  "failure.bothHomes": "两座家都被攻破了。", "failure.abandoned": "玩家主动结束任务；只结算已完成的行动。", "failure.unknown": "战役结束，但没有记录可向玩家展示的原因。",
  "tool.bag": "垃圾袋", "tool.swatter": "电网拍", "tool.trap": "陷阱与设备", "tool.exit": "退出工具模式", "tool.available": "可用", "tool.active": "已启用——按 Esc 退出", "tool.full": "已装满——把整袋拖入垃圾桶", "tool.overheated": "过热——松开并等待冷却", "tool.cooling": "冷却中：热量 {percent}%", "tool.blocked": "战役冻结时不可用", "tool.capacity": "容量 {used} / {capacity}",
  "settings.language": "语言", "settings.uiScale": "界面缩放", "settings.quality": "画质", "settings.intensity": "战役强度", "settings.detection": "桌面感知", "settings.display": "下次运行显示器", "settings.displayDisconnected": "已断开（已保存选择）· {id}", "settings.audio": "音频", "settings.master": "主音量", "settings.music": "音乐音量", "settings.effects": "音效音量", "settings.alerts": "警报音量", "settings.visual": "视觉强度", "settings.motion": "震动与动态效果", "settings.flashes": "闪光", "settings.stains": "污渍", "settings.swarm": "虫群氛围", "settings.visualAlerts": "即使静音，视觉警报仍保持开启。", "settings.tutorial": "显示教学提示", "settings.panelPause": "打开面板时暂停", "settings.diagnostics": "在手动支持包中包含匿名本机故障计数",
  "display.currentRun": "当前运行显示器", "display.current": "当前：{display}", "display.open": "移动当前运行", "display.close": "关闭显示器控制", "display.help": "此处移动当前运行；设置中的显示器选择会在下次运行开始时生效。", "display.choose": "选择目标显示器", "display.page": "显示器 {current} / 共 {total} 个", "display.previous": "上一组显示器", "display.next": "下一组显示器", "display.primary": "主显示器", "display.details": "{width} × {height} 物理像素 · {scale}% 缩放", "display.confirmTitle": "移动到 {display}？", "display.confirmBody": "覆盖层和当前运行将一起移动。请确认你能看到并操作该显示器。", "display.confirm": "确认移动", "display.cancel": "取消", "display.moving": "正在把当前运行移动到 {display}……", "display.moved": "当前运行已移动到 {display}。", "display.failed": "当前运行未能移动。请从托盘开启界面交互，检查显示器列表后重试。", "display.stale": "该显示器已不可用，请重新选择。", "display.unavailable": "当前运行显示器控制不可用。请从托盘开启界面交互，并在原生显示服务重新连接后重试。", "display.awaiting": "覆盖层已移动，正在等待新的桌面表面。", "display.topologyChanged": "显示器布局已变化。请从托盘开启界面交互，刷新列表后再移动当前运行。", "display.noOther": "当前没有其他可用显示器。", "display.retry": "重试", "display.refresh": "刷新显示器",
  "option.low": "低", "option.medium": "中", "option.high": "高", "option.gentle": "温和", "option.standard": "标准", "option.intense": "强烈", "option.desktop": "桌面", "option.practice": "练习", "option.off": "关闭", "option.reduced": "减弱", "option.full": "完整",
  "tutorial.title": "教学", "tutorial.step": "第 {current} / {total} 步", "tutorial.dismiss": "知道了", "tutorial.skipStep": "跳过此步", "tutorial.skipAll": "跳过教学",
  "pause.user": "玩家暂停", "pause.shop": "商店已打开", "pause.research": "研究已打开", "pause.settings": "设置已打开", "pause.tutorial": "教学提示", "pause.detection": "桌面感知暂不可用", "pause.hidden": "紧急隐藏", "pause.unknown": "系统暂停（{id}）",
  "upgrade.cleanerClean": "青年清洁", "upgrade.cleanerMove": "青年移动", "upgrade.cleanerCapacity": "青年背包", "upgrade.frogTongue": "青蛙舌距", "upgrade.frogAttack": "青蛙捕虫冷却", "upgrade.frogDigestion": "青蛙消化", "upgrade.frogBatch": "青蛙单次捕食", "upgrade.frogCapacity": "青蛙累计容量", "upgrade.bagCapacity": "垃圾袋容量", "upgrade.bagEfficiency": "垃圾袋卸载", "upgrade.swatDamage": "电网拍伤害", "upgrade.swatHeat": "电网拍热容量", "upgrade.trapMaintenance": "陷阱维护成本", "upgrade.homeArmor": "两屋最大生命",
  "device.bait": "诱饵盒", "device.glue": "黏胶垫", "device.catcher": "捕虫箱", "device.ladder": "梯子",
  "research.cleaner": "青年", "research.frog": "青蛙", "research.bag": "垃圾袋", "research.swat": "电网拍", "research.trap": "陷阱", "research.home": "家园",
  "lobby.title": "战役大厅", "lobby.subtitle": "选择人偶，让它沿窗口和边缘清洁桌面。及时清理垃圾，控制虫群的食物和繁殖。", "lobby.startTitle": "持续桌面生态", "lobby.startBody": "部分垃圾携带虫卵。虫子会孵化、成长、吃垃圾并繁殖；清走食物后，饥饿的虫子会死去。清空虫群后，桌面生态仍会继续。", "lobby.start": "开始试玩任务",
  "lobby.appearance": "青年外观", "lobby.female": "女性维护员", "lobby.femaleBody": "米白夹克、灰绿工装裤与深色马尾；基础能力完全相同。", "lobby.male": "工装造型", "lobby.maleBody": "原创工装青年；基础能力完全相同。", "lobby.selected": "已选择",
  "lobby.recent": "最近一次结算", "lobby.noRecent": "此档案尚无已完成并结算的任务。", "lobby.mission": "任务", "lobby.run": "战局", "lobby.outcome": "结果", "lobby.score": "有效行动分数", "lobby.reward": "获得研究点", "lobby.researchTitle": "永久研究", "lobby.researchBody": "试玩开放六个分支各前两个节点。研究只能在任务之间购买，并可免费重置。", "lobby.settingsTitle": "本机设置",
  "outcome.victory": "胜利", "outcome.defeat": "失败", "outcome.abandoned": "已放弃", "feedback.busy": "正在保存选择……", "feedback.success": "选择已保存。", "feedback.failure": "操作失败（{reason}）。请查看提示后重试。",
};

export const UI_MESSAGE_KEYS: readonly UiMessageKey[] = Object.freeze(Object.keys(EN) as UiMessageKey[]);

export const UI_MESSAGES: Readonly<Record<Locale, TranslationTable>> = Object.freeze({ en: EN, "zh-CN": ZH_CN });

const placeholders = (value: string): string[] => [...value.matchAll(/\{([A-Za-z][A-Za-z0-9_]*)\}/g)].map(match => match[1]);

export function uiText(locale: Locale, key: UiMessageKey, params: Readonly<Record<string, string | number>> = {}): string {
  return UI_MESSAGES[locale][key].replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (_token, name: string) => {
    if (!(name in params)) throw new Error(`Missing UI translation parameter "${name}" for "${key}"`);
    const value = params[name];
    return typeof value === "number" ? new Intl.NumberFormat(locale, { maximumFractionDigits: 2 }).format(value) : value;
  });
}

export function validateUiMessages(): string[] {
  const defects: string[] = [];
  for (const key of Object.keys(EN) as UiMessageKey[]) {
    const expected = [...new Set(placeholders(EN[key]))].sort().join("|");
    for (const locale of ["en", "zh-CN"] as const) {
      const actual = [...new Set(placeholders(UI_MESSAGES[locale][key]))].sort().join("|");
      if (actual !== expected) defects.push(`${locale}:${key}:${expected}:${actual}`);
    }
  }
  return defects;
}
